language: haskell

ghc:
  - 7.8.2
  - 7.6.3
  - 7.4.2
    
before_install:
  # Fetch the latest feldspar-language from github
  # Note that we will fetch a branch with the same name as the current
  # branch in feldspar-compiler. This is to support CI of new features
  # depending on features in feldspar-language.
  - git clone -v https://github.com/Feldspar/feldspar-language
  - cd feldspar-language && git checkout $TRAVIS_BRANCH || git checkout master
  - echo "Using feldspar-language from " && git rev-parse HEAD
  - cd $TRAVIS_BUILD_DIR

  # Try installing some of the build-deps with apt-get for speed
  # - ./tools/travis-cabal-apt-install $mode feldspar-language/ ./
  - cabal install alex happy
  - cabal install tasty feldspar-language/ ./

